language: php

php:
  - 7.2
  - 7.3
  - 7.4

env:
  global:
    - DEFAULT=1

matrix:
  fast_finish: true

  include:
    - php: 7.2
      env: PREFER_LOWEST=1

    - php: 7.3
      env: PHPCS=1 DEFAULT=0

    - php: 7.4
      env: PHPSTAN=1 DEFAULT=0

before_script:
  - if [[ $TRAVIS_PHP_VERSION != 7.3 ]]; then phpenv config-rm xdebug.ini; fi

  - if [[ $PHPSTAN = 1 ]]; then composer require --dev phpstan/phpstan:^0.12; fi

  - if [[ $PHPSTAN != 1 && $PREFER_LOWEST != 1 ]]; then composer install --no-interaction; fi
  - if [[ $PHPSTAN != 1 && $PREFER_LOWEST = 1 ]]; then composer update --no-interaction --prefer-lowest --prefer-stable; fi

  - echo 'extension = apcu.so' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo 'apc.enable_cli = 1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

script:
  - if [[ $DEFAULT = 1 && $TRAVIS_PHP_VERSION = 7.3 ]]; then vendor/bin/phpunit --coverage-clover=clover.xml; fi
  - if [[ $DEFAULT = 1 && $TRAVIS_PHP_VERSION != 7.3 ]]; then vendor/bin/phpunit; fi

  - if [[ $PHPCS = 1 ]]; then vendor/bin/phpcs -p --extensions=php --standard=vendor/cakephp/cakephp-codesniffer/CakePHP ./src ./tests; fi

  - if [[ $PHPSTAN = 1 ]]; then vendor/bin/phpstan analyse src; fi

after_success:
  - if [[ $DEFAULT = 1 && $TRAVIS_PHP_VERSION = 7.3 ]]; then bash <(curl -s https://codecov.io/bash); fi

notifications:
  email: false
